# Binary parity: fmlib и autocampaignxfm

Запускаются полные trainer/evaluator autocampaignxfm и BinaryTask для product и channel. В каждой Optuna study выполняется три trial с seed 42. Сравнение включает ROC AUC, распределение score, найденные гиперпараметры и время. Разные best params допустимы; основной критерий — близость качества и распределения score.

In [1]:
import json
from pathlib import Path

import polars as pl
from IPython.display import display

from tools.automl_parity.binary import run_comparison

FMLIB_ROOT = next(root for root in (Path.cwd(), *Path.cwd().parents) if (root / 'fmlib').is_dir())
WORKSPACE = FMLIB_ROOT.parent
CONFIG_DIR = FMLIB_ROOT / 'examples/automl/tests/configs'
AUTOCAMPAIGN_ROOT = WORKSPACE / 'autocampaignxfm'
AUTOCAMPAIGN_PYTHON = AUTOCAMPAIGN_ROOT / 'env/bin/python'
assert AUTOCAMPAIGN_PYTHON.is_file()

In [2]:
comparisons = {}
for scope in ('product', 'channel'):
    comparisons[scope] = run_comparison(
        CONFIG_DIR / f'parity_{scope}_autocampaignxfm.yaml',
        CONFIG_DIR / f'parity_{scope}_fmlib.yaml',
        autocampaign_root=AUTOCAMPAIGN_ROOT,
        autocampaign_python=AUTOCAMPAIGN_PYTHON,
    )

2026-08-17 15:38:50,751 INFO run_id=ef3c2ccca78f478cb50e3d0151c644f5 Starting action=train task_config=BinaryTaskConfig backend=boosting engine=catboost env_type=local

<workspace>\fmlib-main\env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-08-17 15:38:52,736] A new study created in memory with name: no-name-0b75ff4a-58f9-4cd4-8b06-36693d52a64c

[I 2026-08-17 15:38:55,156] Trial 0 finished with value: 0.7207840700906365 and parameters: {'iterations': 12, 'depth': 2, 'l2_leaf_reg': 1.0, 'bagging_temperature': 0.25, 'learning_rate': 0.1}. Best is trial 0 with value: 0.7207840700906365.

[I 2026-08-17 15:38:56,649] Trial 1 finished with value: 0.7207840700906365 and parameters: {'iterations': 12, 'depth': 2, 'l2_leaf_reg': 1.0, 'bagging_temperature': 0.25, 'learning_rate': 0.1}. Best is trial 0 with value: 0.7207840700906365.

[I 2026-08-17 15:38:58,106] Trial 2 finished with value: 0.7207840700906365 and parameters: {'iterations': 12, 'depth': 2, 'l2_leaf_reg': 1.0, 'bagging_temperature': 0.25, 'learning_rate': 0.1}. Best is trial 0 with value: 0.7207840700906365.

2026-08-17 15:38:59,268 INFO run_id=ef3c2ccca78f478cb50e3d0151c644f5 Finished action=train

2026-08-17 15:38:59,274 INFO run_id=b554fd943a764dacba1821e123d5bc25 Starting action=predict task_config=BinaryTaskConfig backend=boosting engine=catboost env_type=local

2026-08-17 15:38:59,552 INFO run_id=b554fd943a764dacba1821e123d5bc25 Finished action=predict

2026-08-17 15:40:52,030 INFO run_id=f44b0ed273f64ecd9e2a18ad8e853e42 Starting action=train task_config=BinaryTaskConfig backend=boosting engine=catboost env_type=local

[I 2026-08-17 15:40:53,037] A new study created in memory with name: no-name-d399ff32-7d0d-4f22-9fab-51dd4c028edc

[I 2026-08-17 15:40:54,416] Trial 0 finished with value: 0.7094471909216764 and parameters: {'iterations': 12, 'depth': 2, 'l2_leaf_reg': 1.0, 'bagging_temperature': 0.25, 'learning_rate': 0.1}. Best is trial 0 with value: 0.7094471909216764.

[I 2026-08-17 15:40:55,494] Trial 1 finished with value: 0.7094471909216764 and parameters: {'iterations': 12, 'depth': 2, 'l2_leaf_reg': 1.0, 'bagging_temperature': 0.25, 'learning_rate': 0.1}. Best is trial 0 with value: 0.7094471909216764.

[I 2026-08-17 15:40:56,654] Trial 2 finished with value: 0.7094471909216764 and parameters: {'iterations': 12, 'depth': 2, 'l2_leaf_reg': 1.0, 'bagging_temperature': 0.25, 'learning_rate': 0.1}. Best is trial 0 with value: 0.7094471909216764.

[I 2026-08-17 15:40:57,360] A new study created in memory with name: no-name-9d5a6ba7-a411-409e-81c4-449846f933e2

[I 2026-08-17 15:40:58,381] Trial 0 finished with value: 0.7285957897397006 and parameters: {'iterations': 12, 'depth': 2, 'l2_leaf_reg': 1.0, 'bagging_temperature': 0.25, 'learning_rate': 0.1}. Best is trial 0 with value: 0.7285957897397006.

[I 2026-08-17 15:40:59,371] Trial 1 finished with value: 0.7285957897397006 and parameters: {'iterations': 12, 'depth': 2, 'l2_leaf_reg': 1.0, 'bagging_temperature': 0.25, 'learning_rate': 0.1}. Best is trial 0 with value: 0.7285957897397006.

[I 2026-08-17 15:41:00,451] Trial 2 finished with value: 0.7285957897397006 and parameters: {'iterations': 12, 'depth': 2, 'l2_leaf_reg': 1.0, 'bagging_temperature': 0.25, 'learning_rate': 0.1}. Best is trial 0 with value: 0.7285957897397006.

2026-08-17 15:41:01,211 INFO run_id=f44b0ed273f64ecd9e2a18ad8e853e42 Finished action=train

2026-08-17 15:41:01,218 INFO run_id=4dbb51eb734244549bf5b0a45646fb32 Starting action=predict task_config=BinaryTaskConfig backend=boosting engine=catboost env_type=local

2026-08-17 15:41:01,792 INFO run_id=4dbb51eb734244549bf5b0a45646fb32 Finished action=predict

In [3]:
metric_rows = []
for scope, comparison in comparisons.items():
    raw_metrics = comparison['metrics']['test_roc_auc']
    calibrated_metrics = comparison['metrics'].get('calibrated_test_roc_auc', {})
    for model_name, values in raw_metrics.items():
        calibrated = calibrated_metrics.get(model_name, {})
        metric_rows.append({
            'scope': scope,
            'model': model_name,
            'autocampaignxfm_roc_auc': values['autocampaignxfm'],
            'fmlib_roc_auc': values['fmlib'],
            'absolute_difference': values['absolute_difference'],
            'calibrated_autocampaignxfm_roc_auc': calibrated.get('autocampaignxfm'),
            'calibrated_fmlib_roc_auc': calibrated.get('fmlib'),
            'calibrated_absolute_difference': calibrated.get('absolute_difference'),
            'score_ks': comparison['score_distribution']['ks_statistic'],
            'calibrated_score_ks': comparison['calibrated_score_distribution']['ks_statistic'],
            'best_params_equal': comparison['best_params_equal'],
            'comparison_passed': comparison['passed'],
        })
display(pl.DataFrame(metric_rows))

timing_rows = []
for scope, comparison in comparisons.items():
    timing_rows.append({
        'scope': scope,
        'autocampaignxfm_train_seconds': comparison['timing_seconds']['autocampaignxfm']['total_train_before_predict'],
        'fmlib_train_seconds': comparison['timing_seconds']['fmlib']['total_train_before_predict'],
        'fmlib_predict_seconds': comparison['timing_seconds']['fmlib']['predict'],
    })
display(pl.DataFrame(timing_rows))

shape: (3, 12)
┌─────────┬────────────┬────────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ scope   ┆ model      ┆ autocampai ┆ fmlib_roc ┆ … ┆ score_ks ┆ calibrate ┆ best_para ┆ compariso │
│ ---     ┆ ---        ┆ gnxfm_roc_ ┆ _auc      ┆   ┆ ---      ┆ d_score_k ┆ ms_equal  ┆ n_passed  │
│ str     ┆ str        ┆ auc        ┆ ---       ┆   ┆ f64      ┆ s         ┆ ---       ┆ ---       │
│         ┆            ┆ ---        ┆ f64       ┆   ┆          ┆ ---       ┆ bool      ┆ bool      │
│         ┆            ┆ f64        ┆           ┆   ┆          ┆ f64       ┆           ┆           │
╞═════════╪════════════╪════════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ product ┆ product    ┆ 0.720105   ┆ 0.719635  ┆ … ┆ 0.0377   ┆ 0.0352    ┆ true      ┆ false     │
│ channel ┆ channel:ch ┆ 0.717757   ┆ 0.71648   ┆ … ┆ 0.041    ┆ 0.035233  ┆ true      ┆ false     │
│         ┆ annel_0    ┆            ┆           ┆   ┆          ┆           ┆           ┆           │
│ channel ┆ channel:ch ┆ 0.722183   ┆ 0.71975   ┆ … ┆ 0.041    ┆ 0.035233  ┆ true      ┆ false     │
│         ┆ annel_1    ┆            ┆           ┆   ┆          ┆           ┆           ┆           │
└─────────┴────────────┴────────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

shape: (2, 4)
┌─────────┬───────────────────────────────┬─────────────────────┬───────────────────────┐
│ scope   ┆ autocampaignxfm_train_seconds ┆ fmlib_train_seconds ┆ fmlib_predict_seconds │
│ ---     ┆ ---                           ┆ ---                 ┆ ---                   │
│ str     ┆ f64                           ┆ f64                 ┆ f64                   │
╞═════════╪═══════════════════════════════╪═════════════════════╪═══════════════════════╡
│ product ┆ 62.184945                     ┆ 8.52357             ┆ 0.283241              │
│ channel ┆ 88.478693                     ┆ 9.186872            ┆ 0.581078              │
└─────────┴───────────────────────────────┴─────────────────────┴───────────────────────┘

Полные отчёты каждого запуска сохранены в `outputs/notebook_tests/parity_product/comparison.json` и `outputs/notebook_tests/parity_channel/comparison.json`. Notebook оставляет видимыми как итоговый флаг, так и отдельные численные расхождения.